jobs:
name: Android Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: git clone ${{ github.repository }} .
      - name: Set up Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
      - name: Install dependencies
        run: npm install
      - name: Set up JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
      - name: Build Debug APK
        run: npx react-native run-android --variant=debug
      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease
        uses: actions/upload-artifact@v3
